/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hex.editor;

import hex.editor.Frames.MainWindow;

public class App {
    public static void main(String[] args) {
        HexEditor hexEditor = new HexEditor();
        
    }
}
