/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hex.editor;

public class App {
    public static void main(String[] args) {
        HexEditor hexEditor = new HexEditor();
        
    }
}
